title: Rarescraciu's awesome title version 4
author: GitHub User
email: rares.craciunas@yahoo.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  description version 4
  description version 4
  description version 4
  description version 4

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
